/* Zitat des Tages — 31 Zitate, rotieren deterministisch pro Kalendertag.
   t = Zitattext, s = Quelle (Autor, Werk). */
const QUOTES = [
  { t: "Prüfe, ob es die Dinge betrifft, die in unserer eigenen Macht stehen, oder jene, die es nicht tun; und wenn es etwas außerhalb deiner Macht betrifft, sei bereit zu sagen, dass es dich nichts angeht.", s: "Epiktet, Enchiridion" },
  { t: "Verlange nicht, dass die Ereignisse so geschehen, wie du es wünschst; sondern wünsche, dass sie so geschehen, wie sie geschehen, und es wird dir gut ergehen.", s: "Epiktet, Enchiridion" },
  { t: "Überall zu sein, bedeutet nirgendwo zu sein.", s: "Seneca, Letters from a Stoic" },
  { t: "Lass jede Handlung auf ein Ziel gerichtet und in ihrer Art vollkommen sein.", s: "Marcus Aurelius, Meditationes" },
  { t: "Bedenke bei jeder Angelegenheit, was vorausgeht und was folgt, und dann unternimm sie.", s: "Epiktet, Enchiridion" },
  { t: "Wer also frei sein will, der soll nichts wünschen und nichts ablehnen, das von anderen abhängt; andernfalls muss er zwangsläufig ein Sklave sein.", s: "Epiktet, Enchiridion" },
  { t: "Was vorbeifliegt, muss ergriffen werden.", s: "Seneca, Letters from a Stoic" },
  { t: "Der eigene Geist ist der am meisten von Lärm befreite Ort der Welt, wenn die Gedanken eines Mannes so beschaffen sind, dass sie ihm vollkommene innere Ruhe sichern.", s: "Marcus Aurelius, Meditationes" },
  { t: "Ein Mensch kann selten unglücklich sein, weil er die Gedanken eines anderen nicht kennt; aber wer nicht auf die Regungen seiner eigenen achtet, ist gewiss unglücklich.", s: "Marcus Aurelius, Meditationes" },
  { t: "Denke bei jedem Vorfall daran, dich dir selbst zuzuwenden und zu prüfen, welche Fähigkeit du hast, um damit umzugehen.", s: "Epiktet, Enchiridion" },
  { t: "Nichts ist unglücklicher als die Neugier des Menschen, der überall umherschweift… aber nicht bedenkt, dass es ausreicht, die Göttlichkeit in sich selbst zu verehren.", s: "Marcus Aurelius, Meditationes" },
  { t: "Der weise Mann wird diese Dinge ertragen, aber nicht absichtlich die Konfrontation suchen; er wird den Frieden dem Krieg vorziehen.", s: "Seneca, Letters from a Stoic" },
  { t: "Eine Veränderung des Charakters, nicht ein Tapetenwechsel, ist das, was du brauchst.", s: "Seneca, Letters from a Stoic" },
  { t: "Eine ausgewogene Kombination beider Haltungen ist das, was wir wollen; der aktive Mensch sollte in der Lage sein, die Dinge gelassen zu nehmen, während der zur Ruhe neigende Mensch zum Handeln fähig sein sollte.", s: "Seneca, Letters from a Stoic" },
  { t: "Trägt dies zu meinem Charakter bei?", s: "Via Stoica, What is Eudaimonia?" },
  { t: "Ein guter Charakter ist die einzige Garantie für ein ewiges, unbeschwertes Glück.", s: "Seneca, Letters from a Stoic" },
  { t: "Beginne damit, dir selbst einen Charakter und ein Verhalten vorzuschreiben, das du sowohl allein als auch in Gesellschaft beibehalten kannst.", s: "Epiktet, Enchiridion" },
  { t: "Wenn du dich von der Vernunft leiten lässt und das, was vor dir liegt, mit Fleiß, Kraft und Maßhaltung bewältigst… dann wirst du ein glücklicher Mensch sein.", s: "Marcus Aurelius, Meditationes" },
  { t: "Sei bei nichts, was du tust, widerwillig, egoistisch, unbedacht oder leidenschaftlich.", s: "Marcus Aurelius, Meditationes" },
  { t: "Ich glaube, dass genauso wie körperliches Training vermeintlich unwillkürliche Muskeln in willkürliche verwandelt, eine ähnliche Transformation durch das Training des Geistes erreicht werden kann.", s: "Yukio Mishima, Sun and Steel" },
  { t: "Es bedarf nur eines moderaten Arbeitsaufwands, damit der Geist gedeiht und sich entwickelt. Kultiviere ein Kapital, das die Zeit selbst verbessert.", s: "Seneca, Letters from a Stoic" },
  { t: "Nicht derjenige, der zu wenig hat, ist arm, sondern derjenige, der sich nach mehr sehnt.", s: "Seneca, Letters from a Stoic" },
  { t: "Wenn du dein Leben nach der Natur gestaltest, wirst du niemals arm sein; wenn nach der Meinung der Menschen, wirst du niemals reich sein.", s: "Seneca, Letters from a Stoic" },
  { t: "Wer wenig begehrt, braucht nur wenig. Derjenige hat seinen Wunsch erfüllt, dessen Wunsch es ist, genug zu haben.", s: "Seneca, Letters from a Stoic" },
  { t: "Die großartige ‚Fähigkeit‘ des großen Genies, für das selbst ewiges Leiden ein zu geringer Preis ist, ist der strenge Stolz des Künstlers.", s: "Friedrich Nietzsche, The Birth of Tragedy" },
  { t: "Erhebt eure Herzen, meine Brüder, hoch, höher! Und vergesst mir auch die Beine nicht! Erhebt auch eure Beine, ihr guten Tänzer, und besser noch: steht auch auf dem Kopf!", s: "Friedrich Nietzsche, The Birth of Tragedy" },
  { t: "Denn eine Schwalbe macht noch keinen Sommer, auch nicht ein einziger Tag; und so macht auch ein einziger Tag oder eine kurze Zeit einen Menschen nicht gesegnet und glücklich.", s: "Aristoteles, Nicomachean Ethics" },
  { t: "Gestalte alle deine Handlungen, Worte und Gedanken so, als könntest du in jedem Moment aus dem Leben scheiden.", s: "Marcus Aurelius, Meditationes" },
  { t: "Jeder Tag sollte daher so gestaltet werden, als wäre er derjenige, der das Schlusslicht bildet, der unser Leben abrundet und vollendet.", s: "Seneca, Letters from a Stoic" },
  { t: "Derjenige, der dem Morgen ohne Sorge entgegensieht, kennt eine friedliche Unabhängigkeit und ein Glück, das alles andere übertrifft.", s: "Seneca, Letters from a Stoic" },
  { t: "Es ist deine Pflicht zu überlegen, wie du das meiste aus deinem Leben machen und das Vorhandene zum größten Vorteil nutzen kannst.", s: "Platon (zitiert von Marcus Aurelius), Meditationes" },
];
